const express = require("express");
const guideController = require("../controllers/guideController");
const authController = require("../controllers/authUsers");
const route = express.Router();
route.get("/", guideController.getAllGuides);
route.post("/signup", guideController.insertGuide);
route.post("/login", authController.login);
route.get("/:id", guideController.getGuideById);
route.patch("/:id", guideController.updateGuide);
route.delete("/:id", guideController.deleteGuide);
module.exports = route;
